mediator/med.F90
mediator/med_phases_aofluxes_mod.F90

These commit allows to fix the issue related with ESMF_DistGrid on stampede
**Used hashes/branches:**
**To test CESM application:**
CIME: 6493b342
CAM: nuopc_cap_n31_cam6_1_008/components/cam
CICE: 472a2f29
CISM: 05a64177
CLM: 899b08a9
MOSART: mosart1_0_31_nuopc03
FMS: 3b8096b
CVMIX: 534fc38
MOM: 243bf86c
POP: f4c7f4d
WW3: 2ca8091
FVGFS: f9cd8d6b
**To test FV3 application:**
CIME: 979b021 (cmeps-cime repository)
FV3GFS: c79e18b
CICE: 472a2f2
FMS: 3b8096b
CVMIX: 534fc38
MOM: 243bf86c
**Test suite:**
**To test FV3 application:**
./create_newcase --compset UFS_S2S --res C384_t025 --case ufs.s2s.c384_t025.jan --driver nuopc --run-unsupported
cd ufs.s2s.c384_t025.jan/
./case.setup
./xmlchange DOUT_S=FALSE
./xmlchange STOP_N=1
./xmlchange RUN_REFDATE=2012-01-01
./xmlchange …

fixes ESMF_DistGrid issue on stampede

---

mediator/med.F90
mediator/med_phases_aofluxes_mod.F90

Reverts ESCOMP/CMEPS#11 This is fixed in ESMF level. We don't need to modify CMEPS anymore.

Revert "fixes ESMF_DistGrid issue on stampede"

---

mediator/med_merge_mod.F90

Change Description: Add a check lrank==2 before testing variables. 
Fixes #18 
Testing Completed: scripts_regression_tests.py
CIME HASH: b51b397d

dont check uninitialzed vars, change info to error

---

cime_config/namelist_definition_drv.xml
cime_config/runseq/runseq_CG.py
mediator/esmFlds.F90
mediator/esmFldsExchange.F90
mediator/fd.yaml
mediator/med.F90
mediator/med_io_mod.F90
mediator/med_phases_aofluxes_mod.F90
mediator/med_phases_history_mod.F90
mediator/med_phases_prep_ocn_mod.F90

Change Description: changes needed for mom6 mct/nuopc validation
This PR adds the following:
- attributes of name and units to mediator history files
these attributes now come from querying the NUOPC field dictionary and as a results the routines
`shr_nuopc_fldList_AddMetadata` and `shr_nuopc_fldList_GetMeta` in `esmFlds` are not longer needed
- change  in `fd.yaml` of the alias names for the swpen coming from cice (these were duplicates and now have new names - as a result cice must also have a new hash)
- addition of new cart3d atm->ocn and atm->ice mapping that is triggered by the new config option `mapuv_with_cart3d`. This is currently to to .false. by default - but will be turned on as default in an upcoming tag.
- new run sequence for C and G compsets to match mct run sequence
- set …

changes needed for mom6 mct/nuopc validation

---

cime_config/buildnml
cime_config/config_component.xml

Change Description: Add support for env_workflow.xml 
Tested against cime with some expected failures in Z_FullSystemTest:
FAIL SMS_D_Ln9_Mmpi-serial.f19_g16_rx1.A.cheyenne_intel . (no esmf serial library)
FAIL PRE.f19_f19.ADESP_TEST.cheyenne_intel 
FAIL PRE.f19_f19.ADESP.cheyenne_intel .                          (ERROR: No pause_active flag is set)
FAIL ERS.ne30_g16_rx1.A.cheyenne_intel.drv-y100k        (ESMF_Clock.F90:1695 ESMF_ClockSet() Value out of range  - Internal subroutine call returned Error)
FAIL DAE.ww3a.ADWAV.cheyenne_intel  Unrecognized line ('No initial run signal found for cycle 0
CIME HASH:  d7f56ac

update for workflow change in cime, add error for runseq not found

---

cime_config/config_component_cesm.xml

Change Description: Updates *_NCPL and CPL_ALBAV defaults for MOM6.
Testing Completed: aux_mom
CIME HASH: c2433ef3f9c24bce6c4c276d07cfbac1bed66f90

Updates to mom6 config defaults

---

mediator/med.F90
mediator/med_phases_history_mod.F90

Change Description: Currently, history file alarm is initialized within the first coupling timestep. That means, history files cannot be written until the second timestep because for alarms to turn on, time must advance. With this PR, history alarm gets initialized before run starts. This change fixes issue #31 
Testing Completed: CIME_DRIVER=nuopc scripts_regression_tests.py
CIME HASH: 2b02a76de27e1d9abefcfcb773a69ec58e437e00

Fixes history file write in first cpl timestep

---

drivers/cime/ensemble_driver.F90
drivers/cime/esm.F90
mediator/esmFlds.F90
mediator/esmFldsExchange.F90
mediator/med.F90
mediator/med_fraction_mod.F90
mediator/med_io_mod.F90
mediator/med_map_mod.F90
mediator/med_merge_mod.F90
mediator/med_methods_mod.F90
mediator/med_phases_aofluxes_mod.F90
mediator/med_phases_history_mod.F90
mediator/med_phases_ocnalb_mod.F90
mediator/med_phases_prep_atm_mod.F90
mediator/med_phases_prep_glc_mod.F90
mediator/med_phases_prep_ice_mod.F90
mediator/med_phases_prep_lnd_mod.F90
mediator/med_phases_prep_ocn_mod.F90
mediator/med_phases_prep_rof_mod.F90
mediator/med_phases_prep_wav_mod.F90
mediator/med_phases_profile_mod.F90
mediator/med_phases_restart_mod.F90
mediator/med_time_mod.F90
mediator/med_utils_mod.F90

Moved shr_nuopc_xxx.F90 files back to the mediator/ directory with renaming
Change Description: moved shr_nuopc_xxx.F90 files back to the mediator/ directory and renamed them med_xxx.F90 instead
Testing Completed: testlist_driver.xml - results were bfb with oct30
(did not run CIME_DRIVER=nuopc scripts_regression_tests.py since full test suite was run and bfb was validated)
CIME HASH: 2cd9068ba

moved shr_nuopc_xxx.F90 files back to the mediator/ directory with renaming

---

cime_config/runseq/runseq_CG.py
cime_config/testdefs/testlist_drv.xml

Change Description: expanded new testlist for CESM components 
This PR brings expanded testing capability of the NUOPC caps in CESM components and
and updated app_cesm-cmeps to point to updated component hashses
Testing Completed: testlist_drv.xml
- compared to nov03 baselines and generated nov08 baselines 
- the following tests had baseline differences compared to nov03
```
ERR_Vnuopc_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io
ERS_Vnuopc_Ld5.T62_g17.C.cheyenne_intel
ERS_Vnuopc_Ld5.T62_g17.G.cheyenne_intel
ERS_Vnuopc_Ld5.T62_t061.CMOM.cheyenne_intel
ERS_Vnuopc_Ld5.T62_t061.GMOM.cheyenne_intel
ERS_Vnuopc_Ln11.f19_f19_mg17.I2000Clm50SpGs.cheyenne_intel.clm-default
ERS_Vnuopc_Ln11.f19_f19_mg17.I2000Clm50SpRsGs.cheyenne_intel.clm-default …
```

new testlist for CESM components

---

cime_config/buildnml
cime_config/config_component.xml
cime_config/namelist_definition_drv.xml
cime_config/runseq/driver_config.py
drivers/cime/esm.F90
mediator/med.F90
mediator/med_phases_ocnalb_mod.F90

move orbital calculations to the noupc caps
- The orbital updates have now been moved to every model cap that requires an orbital calculation. This is required since the run sequence in nuopc is not done in hard-wired code (like cpl7) but rather in an run sequence ascii file. So calls to update the orbital calculation cannot be done in one place (like in the cpl7 driver. 
- Component caps that had orbital dependencies were modified - and round-off level differences appeared in some cases.
- This PR is dependent on the CIME PR #3373
Testing Completed: testlist_drv.xml
- New baselines were created for jan20 that only had differences from the orbital migration to the caps.
- The latest baselines jan26 are bfb with jan20.
app_cesm-cmeps HASH: fe19c4e

move orbital calculations to the noupc caps

---

mediator/med_fraction_mod.F90
mediator/med_io_mod.F90
mediator/med_map_mod.F90
mediator/med_phases_prep_glc_mod.F90
mediator/med_phases_prep_rof_mod.F90

gfortran doesn't accept the lowercase __line__
Testing Completed: Just tested the build on my mac with gfortran, with:
`./create_newcase --case $scratch/test_control_0224b --compset I2000Clm50SpRsGs --res f45_f45_mg37 --run-unsupported --driver nuopc`
NOTE: This test was done with a similar set of changes off of an older version of the code (181ff1ed9dfb279e619e8a2173f43baf7bf1dce3). I have NOT tested this version directly.
CIME HASH: Above testing was done with 569aa6ec8

Change all occurrences of the __line__ macro to be uppercase __LINE__

---

cime_config/config_component.xml

Add EXTRA_MACHDIR and NONLOCAL xml variables.
This is needed to work with the changes in
https://github.com/ESMCI/cime/pull/3508
This exactly mimics the change to config_component.xml in the mct driver in that cime PR.
Just ran `CIME_DRIVER=nuopc ./scripts_regression_tests.py J_TestCreateNewcase`
CIME HASH: `f69fa6d11`

Add EXTRA_MACHDIR and NONLOCAL xml variables

---

.gitignore
cime_config/config_component_cesm.xml

Set the default ROF_NCPL for mizuRoute.
Testing Completed: SMS_D_P1x1_Vnuopc_Ld5.5x5_amazon_r05.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default
this test requires branches for mizuRoute, ctsm, and cime.
Running
env CIME_DRIVER=nuopc scripts_regression_tests.py
is failing, but I don't think it's because of my changes.
CIME HASH: cime5.8.23-10-g916d9927b

Set default ROF_NCPL for mizuroute

---

mediator/fd_nems.yaml

Adds nems-specific field names and aliases for coupling ww3 through connectors in UFS-S2S-model
@mvertens 
Are changes expected to change answers (and if so in what way)?
No
- machines:
- description: baselines created
- branch: …

ww3 additions to fd_nems.yaml

---

mediator/Makefile
mediator/med.F90

It fixes issues related to the latest CMEPS PR #68 for the NEMS application.
CMEPS Issues Fixed (include github issue #): https://github.com/ESCOMP/CMEPS/issues/68
Are changes expected to change answers (and if so in what way)? No
- machines: Cheyenne
- details (e.g. failed tests): master (cf4e44c)
```
======================================================================
FAIL: test_bless_test_results (__main__.Q_TestBlessTestResults)
----------------------------------------------------------------------
Traceback (most recent call last):
File …
```

fix for NEMS app

---

cime_config/config_component_cesm.xml

Changes the default value of TFREEZE_SALTWATER_OPTION for MOM6 from mushy to linear_salt.
Test suite: SMS.CMOM.T62_t061, SMS.C.T62_t061
Test baseline:
Test namelist changes: changes xml var TFREEZE_SALTWATER_OPTION for MOM6 only
Test status: changes answers for MOM6 only

Update TFREEZE_SALTWATER_OPTION value for MOM6

---

.github/pull_request_template.md
cime_config/buildexe
cime_config/buildnml
cime_config/config_pes.xml
cime_config/namelist_definition_drv_flds.xml
cime_config/runseq/driver_config.py
cime_config/runseq/gen_runseq.py
cime_config/runseq/runseq_D.py
cime_config/runseq/runseq_TG.py
cime_config/runseq/runseq_general.py
mediator/esmFlds.F90
mediator/esmFldsExchange_nems_mod.F90
mediator/fd_cesm.yaml
mediator/fd_nems.yaml
mediator/med.F90
mediator/med_fraction_mod.F90
mediator/med_map_mod.F90
mediator/med_merge_mod.F90
mediator/med_phases_prep_atm_mod.F90
mediator/med_phases_prep_ice_mod.F90
mediator/med_phases_prep_ocn_mod.F90

Clean up and changes to be consistent with upcoming NEMS changes 
This PR also provides the ability to create compsets and tests for there is only 1 component (e.g. data) and the mediator.
Contributors other than yourself, if any: @DeniseWorthen 
None
Are changes expected to change answers (and if so in what way)?
No  - bit-for-bit
No
- machines:
- details (e.g. failed tests): ran testlist_drv.xml, compared to jun18 baselines and created jul05 baselines …

cleanup and changes to be consistent with nems 

---

cime_config/buildnml
cime_config/config_component.xml

This PR aims to fix the CIME interface for definition of coupling mode. "nems_orig_active" was not using in the CMEPS code. So, it is replaced with "nems_orig".
CMEPS Issues Fixed (include github issue #): CIME COUPLING_MODE option is fixed
- machines:
- description: …

Minor fix for CIME interface

---

drivers/cime/esm_time_mod.F90
mediator/esmFldsExchange_cesm_mod.F90
mediator/med_fraction_mod.F90
mediator/med_map_mod.F90
mediator/med_phases_prep_glc_mod.F90
mediator/med_phases_prep_lnd_mod.F90
mediator/med_phases_prep_rof_mod.F90

Bug fixes and cleanup of map and fractions mod 
This fixes a substantial bug in that the ice/ocean mask was mapped from the ocean mesh to the atm mesh using conservative mapping with a normtype of DSTFRAC rather than a normtype of DSTAREA. The result was that the land fraction on the atm mesh was always just 0/1 and the ocean fraction in non-polar regions was 0/1 on the coasts. This PR fixes this. 
Also, as part of this PR a clean up of `med_map_mod.F90 `was done for generating the maps that were needed by `med_fraction_mod.F90.`
CMEPS Issues Fixed (include github issue #): #106 
Testing performed if application target is …

changes for bugfix fractions

---

mediator/esmFldsExchange_hafs_mod.F90

This change splits esmFldsExchange_hafs_mod.F90 into two subroutines for maintenance purposes. The interface into esmFldsExchange_hafs has not changed but will call into one of the following subroutines.
esmFldsExchange_hafs_advt (advertise): advertise import and export fields
esmFldsExchange_hafs_init (initialize): establish field mapping and merges after field connections establish
Contributors other than yourself, if any: none
- machines:
- machines and compilers: Cheyenne / Intel and MPT combination shipped …

Clean up esmFldsExchange_hafs_mod.F90 file

---

mediator/Makefile
mediator/med_diag_mod.F90

If budget variables are not in config file set them to 0 and continue
CMEPS Issues Fixed (include github issue #): #116 
- machines: cheyenne
- details (e.g. failed tests):  
- machines and compilers: cheyenne intel 
- details (e.g. failed tests): All pass  oct22 baselines generated
- description:
- branch: nuopc_dev
- …

Diags optional in configfile

---

mediator/esmFlds.F90
mediator/esmFldsExchange_cesm_mod.F90
mediator/med_fraction_mod.F90

fixes for how river runoff is sent to ocean
New mapping types were created to account for custom rof->ocn mappings that are different than conservative mapping
CMEPS Issues Fixed:#118
- machines:
- machines and compilers: cheyenne, intel aux
- details (e.g. failed tests): compared to oct22 and generated oct26 in cmeps_baselines 
- description:
- repository …

fixes for how river runoff is sent to ocean

---

cime_config/config_component.xml
cime_config/runseq/runseq_general.py
mediator/med_phases_aofluxes_mod.F90

Fixes test ERI_Ln9_Vnuopc.f09_g16.X by removing aofluxes and ocnalb calculations
- machines: cheyenne intel 
- details (e.g. failed tests):  All PASS
- machines and compilers: cheyenne intel
- details (e.g. failed tests):generate oct27  SMS_Vnuopc.f19_g17.X.cheyenne_intel  failed BASELINE (expected)
- description: …

remove albedo from the X compset

---

Makefile
mediator/Makefile
mediator/med_utils_mod.F90
nuopc_cap_share/nuopc_shr_methods.F90

This PR aims to support CDEPS as a part of HAFS application and including following modifications:
- PIO and genf90 are updated to latest versions. This is required to support CDEPS that requires newer version of PIO. Currently, CDEPS uses PIO installed along with CMEPS under HAFS application
- It makes PIO initialization optional. HAFS application initializes PIO in the NEMS driver because HAFS application has both CMEPS and CDEPS and both of them requires PIO
- machines: Cheyenne …

Modifications for HAFS+CDEPS integration

---

cime_config/runseq/runseq_general.py
mediator/med.F90
mediator/med_diag_mod.F90
mediator/med_map_mod.F90
mediator/med_phases_prep_lnd_mod.F90

fixed bugs in med_phases_prep_lnd and med_phases_diag_mod
1.  In med_phases_prep_lnd.F90 the call the map_glc2lnd was called AFTER the merge and it should have been called before.
Also, it is now only called multiple times if CISM is in evolve mode.
2. There were several buts in the med_diag_mod.F90 that are now fixed.
3. med_phases_diag_ocn was not included in the nuopc.runseq for a B1850 case - this has now been fixed.
CMEPS Issues Fixes: #126 
- machines:
- details (e.g. …

fixed bugs in med_phases_prep_lnd and med_phases_diag_mod

---

mediator/med_phases_prep_lnd_mod.F90

This undoes the med_phases_prep_lnd changes introduced in PR#129
- machines:
- machines and compilers: cheyenne, intel
all of the tests are now bfb with the nov03 baseline but not with the nov06 baseline
new nov15 baseline created
- description: …

fix med_phases_prep_lnd problem introduced in PR#129

---

cime_config/runseq/runseq_general.py

Previously, CISM was being called at the start of December 31, with data
from December 31 of the previous year through December 30 of the current
year. The desired behavior is for CISM to be called at the end of
December 31, with data from January 1 of the current year through
December 31 of the current year. This commit fixes that behavior.
Contributors other than yourself, if any: @mvertens 
- machines: …

Call GLC at the end of the day rather than the start

---

cime_config/testdefs/testlist_drv.xml
drivers/cime/esm.F90
drivers/cime/esm_time_mod.F90
drivers/cime/esm_utils_mod.F90
mediator/med_phases_post_glc_mod.F90
mediator/med_utils_mod.F90

Port to the nag fortran compiler.   
- machines: izumi, nag compiler
- details (e.g. failed tests): 
- machines and compilers: izumi, nag
- details (e.g. failed tests): All tests using FMS fail
- description:
- description: …

changes to get nag 6.2 compiler working

---

drivers/cime/esm.F90

This resolves a compilation bug fix to esm.F90 - only effects CESM. Changes required in PR #164 introduced compilation problems that this now fixes.
- machines:
- description:
Testing performed if application target is …

compilation bug fixes

---

.github/workflows/bumpversion.yml

The bumpversion github action was introduced in PR #164 with dryrun=True.  Now satisfied that it is working correctly
this PR will change dryrun=False and set the first version to v0.1.0
- machines:
- description:
Testing …

pr to impliment automatic versioning in cmeps repo

---

cime_config/config_component.xml

changes to get ctsm LILAC mode to work
This is a minor bugfix that only effects CESM workflow and configurations.
The LND_DOMAIN_FILE and LND_DOMAIN_PATH need to be kept in cime_config/config_component.xml 
until LILAC no longer uses the ctsm namelist variables fatmlndfrc (which is obtained from these xml variables)
Only a LILAC test was performed to verify that this bugfix worked.
- machines:
- details (e.g. …

changes to get ctsm LILAC mode to work

---

mediator/esmFlds.F90
mediator/med_map_mod.F90

addition of bilnr_cart3d mapping
Addition of bilinear cart3d mapping in addition to patch cart3d. This is used to map u,v from source to destination meshes. This new addition is needed to validate GMOM cases in CESM. 
- machines:
- description: …

addition of bilnr_cart3d mapping

---

mediator/med.F90

update for getting the glc present flag set correctly with nag compiler
The following ctsm test - SMS_D_Ld5_Vnuopc.f10_f10_mg37.I2000Clm50BgcCrop.izumi_nag.clm-irrig_alternate passed on cheyenne with intel but failed on izumi with nag. This bugfix corrects the if-present logic for GLC and permits the test to successfully pass now on izumi.
ran SMS_D_Ld5_Vnuopc.f10_f10_mg37.I2000Clm50BgcCrop.izumi_nag.clm-irrig_alternate successfully on izumi.

update for getting the glc present flag set correctly with nag compiler

---

cime_config/config_component_cesm.xml
cime_config/testdefs/testlist_drv.xml

bug fix for co2 in config_components_cesm.xml and addition of tests to testlist_drv.xml for cesm testing
This PR only effects the CESM cime_config directory. 
No testing was done - since these are just additions to the automated test suite for cesm

cesm: bug fix for C1850ECO co2 and additional cesm tests

---

cime_config/namelist_definition_drv.xml
mediator/med.F90
mediator/med_constants_mod.F90
mediator/med_internalstate_mod.F90
mediator/med_io_mod.F90
mediator/med_phases_prep_ice_mod.F90
mediator/med_phases_prep_ocn_mod.F90

This change only effects CESM compsets
This adds the capability currently only activated by CESM C and G compsets (with POP not MOM) to have a precip factor sent by POP to the mediator that is then applied to scale atmosphere rain and snow going back to the ocean and sea-ice (in this case POP and CICE/DICE). In the current testing, the precip factor was only set to 1 by POP - as a result, this PR does not change any baselines.
- Verified manually that for SMS_Ld1_Vnuopc.T62_g17.G.cheyenne_intel.pop-default, the scaling …

add functionality for ocean precip scaling for CESM

---

.github/workflows/extbuild.yml
cime_config/buildexe
cime_config/config_component.xml
cime_config/config_component_cesm.xml
cime_config/config_component_ufs.xml
cime_config/namelist_definition_drv.xml
cime_config/testdefs/testlist_drv.xml
drivers/cime/esm.F90
drivers/cime/esmApp.F90
drivers/cime/esm_utils_mod.F90
mediator/med.F90
mediator/med_utils_mod.F90

Fixes the avgdt variable to output in correct units of wallclock seconds per simulation day.
In the CESM driver only, add the nthreads value from nuopc.runconfig to each components attributes. Since the CESM driver is include with CMEPS - this is in fact a CMEPS change but only relevant to the driver.
- machines:
- machines and compilers: cheyenne intel, baseline is apr05
Testing performed …

fix avgdt variable and add nthreads value to gcomp

---

drivers/cime/esm.F90

Fix setting of scol_spval for single column functionality 
This is a simple fix for CESM single column functionality. This ONLY effects the CESM NUOPC driver code.
validated that SMS_D_Ln9_Vnuopc.T42_T42.FSCAM.cheyenne_intel.cam-scam_mpace_outfrq9s now works using cesm2_3_alpah02d hash
- hash: tag for cesm2_3_alpah02d

fix setting of scol_spval for single column functionality 

---

mediator/med_diag_mod.F90

Correct the accumulation of budget diagnostics
- machines: cheyenne / intel
- machines and compilers: cheyenne / intel
- description:
- description:
Hashes used for …

some corrections to the med diag calculations

---

.github/pull_request_template.md
mediator/med.F90
mediator/med_diag_mod.F90
mediator/med_internalstate_mod.F90

Create a diags.log file with the budget calculation results, this is moved from med.log
- machines: cheyenne / intel
- description:
- description: …

write diags to a seperate file

---

mediator/med_diag_mod.F90
mediator/med_phases_prep_ice_mod.F90
mediator/med_phases_prep_ocn_mod.F90

This fixes the budget table to have the correct land ice runoff value and balance the runoff sent to the ocean.
This PR does not affect any UFS configuration, since the UFS does not use the budget tables at this point.
Fixes #179 
Ran a B1850 f19_g17 case for 3 months and verified that the budget table looked correct with this term
- description:
- branch: …

fixes to land ice runoff in budget table

---

mediator/med.F90
mediator/med_diag_mod.F90

Fixes #188 where budgets are not written out for December or annually for a 1 year run
The fix is to use nexttime rather than currtime to trigger budget output. This is consistent with the time stamp of history and restart files as well in cmeps.
Fixes: #188 
This only effects CESM configurations. 
- Verified that an A compset at f19_g17 run for a year with budgets turned on produced both annual budget information as well as a budget entry for month 12.
- Verified that for a 3 month run, B1850 at f19_g17, budgets were created for month 3 and …

Fix for budget annual budget output

---

cime_config/runseq/runseq_general.py
mediator/med_diag_mod.F90

Bug fixes for CESM 1850 mct/nuopc validation - including memory leak in med_diag_mod.F90.
These are changes needed to the budgets and run sequence needed that were needed to fix problems in the B1850 mct/nuopc validation.
Contributors other than yourself, if any: @jedwards4b 
CMEPS Issues Fixed: #190 #197 
5 year B1850 1 year simulation was run
- tag: cesm2_3_alpha03a

Bug fixes for CESM 1850 mct/nuopc validation

---

cime_config/config_component.xml
mediator/esmFlds.F90
mediator/esmFldsExchange_hafs_mod.F90
mediator/med.F90

Remove the ifdef which assured that the version of ESMF was 8 or greater.   Version 8 or greater is always required so this is just a cleanup.   Also added the CASE_HASH variable which is used by cime to establish provenance. 
- machines: cheyenne intel …

remove the version ifdef and add the CASE_HASH variable

---

cime_config/config_component.xml
cime_config/namelist_definition_drv.xml
mediator/esmFldsExchange_cesm_mod.F90

Remove some unused namelist variables: glc_nx, glc_ny, and some glc2lnd and lnd2glc mapping file variables.
In addition to doing some general cleanup, the motivation for removing these is because they will be hard to support with the upcoming capability to have multiple GLC grids.
Contributors other than yourself, if any: @mvertens provided general input
- machines: cheyenne
- Testing run in the context of cesm2_3_beta03
- Two tests failed; these also fail from out-of-the-box cesm2_3_beta03:
- …

Remove unused namelist variables

---

cime_config/namelist_definition_drv.xml
cime_config/namelist_definition_modelio.xml

With my upcoming fix for https://github.com/ESMCI/cime/issues/3984, I
was getting some failures due to namelist variables that weren't
properly defined.
(1) mediator_read_restart: since this is set in the code rather than via
the normal mechanism, I think it's appropriate to have
skip_default_entry="true" here.
(2) ESP's pio_netcdf_format: I'm not positive that the way I've set it
is correct, but it seems more correct than before.
Contributors other than yourself, if any: none
- machines:
- machines and …

Fix namelist variables that weren't being set

---

drivers/cime/esmApp.F90

it turns out that the mpi module does not support functions in the only clause - this is supported in mpi_f08, but that module also changes the type of mpi variables in fortran
- machines:
- description:
Testing performed …

remove only clause for use mpi

---

drivers/cime/esm_time_mod.F90
mediator/med_time_mod.F90

Add support to esm_time_mod.F90 for stop option 'date'.  Change some ESMF log info messages to esmf log error. 
CMEPS Issues Fixed: #192 
Hand tested  SMS_Vnuopc.f19_g17.X with STOP_DATE=00010106 and STOP_OPTION='date'
- machines: cheyenne intel
- machines and compilers: cheyenne intel
- description: …

add support for stop_option date

---

cime_config/buildexe
cime_config/buildnml
drivers/cime/esm.F90

Add code to buildexe script to check that ESMF VERSION is new enough.  ESMF 8.1 is required unless ESMF_AWARE_THREADING is enabled which requires 8.2.0
- machines: cheyenne intel (all pass)
- description:
Testing performed …

esmf aware threading now works with esmf 8.2.0b10 or newer

---

cime_config/buildexe
cime_config/buildnml
cime_config/runseq/driver_config.py
cime_config/runseq/gen_runseq.py
cime_config/runseq/runseq_D.py
cime_config/runseq/runseq_TG.py
cime_config/runseq/runseq_general.py

Explicitly use python3 as required by cime after PR https://github.com/ESMCI/cime/pull/4015
- machines:
- description:
- description: …

change all shebangs to explicitly use python3

---

cime_config/config_component.xml
nuopc_cap_share/nuopc_shr_methods.F90

Fix unitialized value in timeInit function, remove unused ifdays0 option. 
- machines:
- description:
- description:
Hashes used for …

fix unitialized variable in timeInit, remove option ifdays0

---

.github/workflows/extbuild.yml
cime_config/config_component_cesm.xml
cime_config/runseq/gen_runseq.py
cime_config/runseq/runseq_general.py
drivers/cime/esm_time_mod.F90
mediator/esmFldsExchange_cesm_mod.F90
mediator/med.F90
mediator/med_diag_mod.F90

new run sequence for B1850 nuopc validation
This PR requires ESMF https://github.com/esmf-org/esmf/releases/tag/ESMF_8_2_0_beta_snapshot_13 and later snapshots.
With this new snapshot, this PR does the following:
1) Enables a new run RASM_OPTION1 sequence for fully coupled CESM nuopc simulations. 
The new run sequence will look like the following:
```
@432000
@10800
@3600
@1800
MED med_phases_aofluxes_run
MED med_phases_prep_ocn_accum
MED med_phases_ocnalb_run
MED med_phases_diag_ocn
@@3600
MED med_phases_prep_ocn_avg
MED -> OCN :remapMethod=redist
@@
```
With this new run sequence, careful comparison with the RASM_OPTION1 cesm simulation validated this configuration for NUOPC with POP.
2) A fix to the budget table has been put in place to fix problems with MOM6 budgets when running a …

new run sequence for B1850 nuopc validation

---

cime_config/config_component_cesm.xml

fix typo in config_component_cesm.xml (cesm only)
This fixes a typo in config_component_cesm.xml and is needed as a high priority for cesm2_3_alpha05b.
- machines:
- machines and compilers cheyenne/gnu
- details (e.g. failed tests): verified that previous failed test ERS_Vnuopc.T62_g37.G.cheyenne_gnu.pop-cice can now be created
Testing performed if application …

fix typo in config_component_cesm.xml (cesm only)

---

cime_config/runseq/runseq_general.py

fixed run sequence bug for G and C compsets (only for CESM)
This PR fixes generated run sequence bug for G and C compsets  that were introduced in the PR https://github.com/ESCOMP/CMEPS/pull/215
Testing performed if application target is CESM:(either UFS-S2S or CESM testing is required): Manual examination of run sequence
- machines:
- description: …

fixed run sequence bug for G and C compsets (only for CESM)

---

mediator/esmFldsExchange_cesm_mod.F90

fix nag compilation problem
This lightweight PR fixes a nag compilation problem. 
- machines:
- machines and compilers izumi/intel
- details (e.g. failed tests): Verified that the following test now builds SMS_D_Ld3_Vnuopc.f45_g37_rx1.A.izumi_nag
- description:
Testing performed if application …

fixed nag compilation problem

---

cime_config/namelist_definition_drv.xml

fix for ERS restart problem
This fixes problems in cesm ERS tests introduced in #221 
Contributors other than yourself, if any: jedwards4b
CMEPS Issues Fixed: issue not introduced
- machines:
- machines and compilers cheyenne/intel
- details (e.g. failed tests): validated that previous broken test ERS_Vnuopc_Ln5.f19_f19_mg17.F2000Nuopc.cheyenne_intel.cam-nuopc_cap  now works
- description:
- …

fix for ERS restart problem

---

cime_config/namelist_definition_drv_flds.xml
mediator/esmFldsExchange_cesm_mod.F90
mediator/fd_cesm.yaml

Add ozone field from atm -> lnd, and namelist definition for the atm_ozone_frequency variable which will appear in drv_flds_in.
This will work together with changes in CAM (to send ozone and set atm_ozone_frequency), CESM_share (to facilitate reading atm_ozone_frequency) and CTSM (to receive ozone and read atm_ozone_frequency), but the changes here can be brought in independently of those changes.
Contributors other than yourself, if any: @mvertens 
- machines: …

Add ozone field from atm -> lnd

---

cime_config/namelist_definition_drv.xml
cime_config/testdefs/testlist_drv.xml
mediator/med.F90
mediator/med_diag_mod.F90
mediator/med_internalstate_mod.F90
mediator/med_map_mod.F90
mediator/med_phases_aofluxes_mod.F90

bug fixes for new agrid/ogrid and restart functionality
1. add fixes for computing aofluxes on both agrid and xgrid in compsets with data ocean and active atm (i.e. F/Q compsets in CESM)
2. fix problem associated with running ERS/ERR tests with new introduction of write_restart_at_endofrun
CMEPS Issues Fixed: None (no issues were raised for the problems being fixed)
- machines:
- details (e.g. failed tests): 
-  bfb compared to baseline  cmeps0.13.22, 
- verifed that …

fix aoflux agrid/xgrid problems found in testing

---

cime_config/buildexe
cime_config/buildnml
cime_config/runseq/gen_runseq.py

We were generating a modelio namelist per component instance for cmeps but then only looking for one per component in the fortran.  There really isn't any compelling reason to have one of these per instance, so I have changed the generator to only produce one per component.   This resolves the poor performance of multi instance IO in nuopc.    
- machines:
- …

only one shared modelio namelist per component

---

cime_config/buildexe
cime_config/buildnml
cime_config/runseq/gen_runseq.py
mediator/esmFldsExchange_cesm_mod.F90
mediator/med.F90
mediator/med_diag_mod.F90
mediator/med_internalstate_mod.F90
mediator/med_merge_mod.F90
mediator/med_methods_mod.F90
mediator/med_phases_history_mod.F90
mediator/med_phases_post_glc_mod.F90
mediator/med_phases_post_lnd_mod.F90
mediator/med_phases_prep_atm_mod.F90
mediator/med_phases_prep_ice_mod.F90
mediator/med_phases_prep_lnd_mod.F90
mediator/med_phases_prep_ocn_mod.F90
mediator/med_phases_prep_rof_mod.F90
mediator/med_phases_prep_wav_mod.F90
mediator/med_phases_restart_mod.F90

refactor accum field bundles and cleanup of mediator phase InitializeIPDv03p4
This PR does several things.
1. The accumulated import field bundles are no longer arrays and have been removed from `med_internalstate_mod.F90`. All import accumulator field bundles are now module variables in  `med_phases_prep_rof_mod.F90` and `med_phases_prep_glc_mod.F90`. In both of these cases accumulation is done using the import field bundle on the import grid and the averaged, mapped and merged to the export field bundle. 
2. The accumulated export field bundles is no longer an array and only refers to ocean export accumulation. This field bundle now appears in the following section in `med_internalstate_mod.F90`.
```.F90
! Accumulators for export field bundles
type(ESMF_FieldBundle) :: FBExpAccumOcn …
```

refactor accum field bundles

---

mediator/esmFldsExchange_cesm_mod.F90
mediator/fd_cesm.yaml

Pass tributary water depth and channel bankfull depth from rof to lnd
- machines:
- description:
- description:
- …

add new rof to lnd field

---

mediator/med_phases_restart_mod.F90

fix restart problem in lnd->rof accum in cmeps0.13.27 #231
The lnd->rof accumulation fields are not being written to or read from the restarts with PR cmeps0.13.27 and this PR fixes that.
This will only effect CESM configurations.
CMEPS Issues Fixed: #231 
verified that cesm test ERS_Vnuopc_Ln9.f09_f09_mg17.F2000climo.cheyenne_intel.cam-outfrq9s
- tag: cesm2_3_beta05

fixed restart problem for aux_cam and aux_clm tests

---

cime_config/namelist_definition_drv.xml

check_input_data needs this flag to properly download mesh files. 
Change was tested by running the aux_cmeps test suite with flag  --input-dir /glade/scratch/jedwards/inputdata/  to force a new download of inputdata. 
CMEPS Issues : Fixes #196 
- machines:
- description: …

add flag for check_input_data

---

cime_config/buildnml
cime_config/namelist_definition_drv.xml
mediator/med_diag_mod.F90

CESM budget table updates needed for MOM6
This PR targets budget table fixes and updates needed when using MOM6 as the ocean component in CESM.
In particular a new salt budget table is used when MOM6 is present and is not there when POP is present.
This PR should not effect non-CESM applications since they currently do not use the budget module.
Contributors other than yourself, if any: @jedwards4b 
Are changes expected to change answers? No - bit for bit.
Any User Interface Changes (namelist or namelist defaults changes)? Yes. Addition of `budget_table_version` to `nuopc.runconfig.` For POP, this is set to `v0` and for MOM6 its set to `v1`.
1. On cheyenne, ran …

budget table updates needed for MOM6

---

cime_config/namelist_definition_drv.xml
mediator/med_phases_history_mod.F90

This fixes the bug for ERI tests.
This makes `hist_option` and `hist_n` for instantaneous history files for all components module variables with the name
`hist_option_all_inst` and `hist_n_all_inst`.
CMEPS Issues Fixed: #247 #243 
Are changes expected to change answers? No (bit-for-bit)
Testing performed:
Verified that failed test ERI.T62_g16.C1850ECO.cheyenne_intel.pop-ecosys now passes.
Hashes used for testing: CESM: cesm2_3_alpha07a (pre tag)

bugfix for #247

---

mediator/med_io_mod.F90
mediator/med_phases_history_mod.F90

Allows the inst and avg history files for the ATM to be written on the cubed sphere tiles instead of the mesh by setting the configuration variable `` history_tile_atm`` = ``cubed sphere tile size`` (e.g. 96,192,384).
CMEPS Issues Fixed (include github issue #): NOAA-EMC/CMEPS [#59](https://github.com/NOAA-EMC/CMEPS/issues/59)
verified that ERS_Ld7.f19_g17.B1850.cheyenne_intel.allactive-defaultio was bfb with cesm2_3_alpha07b
- description: Tested ufs-weather-model develop branch against a …

Optional tiled history files for ATM

---

cime_config/namelist_definition_drv.xml
mediator/esmFldsExchange_cesm_mod.F90

Add a namelist trigger to turn on passing of channel depth fields needed for the hillslope model.
Contributors other than yourself, if any: @mvertens @swensosc 
Fixes #241
Fixes #245
- [ x] bit for bit
- [ x] Yes
Add flds_r2l_stream_channel_depths to ALLCOMPS_attributes config file
- [ x] (other) please described in detail
- machines and compilers: cheyenne_intel
SMS_D_Ld5_Vnuopc.f10_f10_mg37.I2000Clm50BgcCrop.cheyenne_intel.mosart-default
Can add flds_r2l_stream_channel_depths to user_nl_cpl and tdepth fields are …

Namelist trigger for passing channel depth fields from ROF to LND

---

cime_config/config_component.xml
cime_config/namelist_definition_drv.xml

Adds variable DIN_STAGING_ROOT for systems that cannot access the inputdata location from compute nodes. See https://github.com/ESMCI/cime/pull/4118 for details. 
- machines:
- description:
Testing performed if application …

adds DIN_STAGING_ROOT variable

---

mediator/med_phases_aofluxes_mod.F90
mediator/med_phases_prep_atm_mod.F90

Fixes to fix budget differences found between the aoflux calculation on the xgrid and aoflux calculatino on the ogrid.
The key difference is that mapping from the xgrid to the agrid is now done so that fields on the xgrid are normalized by the current open ocean fraction on the xgrid and then mapped and subsequently divided by the ocean fraction on the atm grid.
- machines:
- machines and compilers: cheyenne_intel
- details (e.g. failed tests): generated baselines for cesm2_3_alpha07c and …

changes to fix budget issues for aoflux on xgrid

---

mediator/med_phases_aofluxes_mod.F90

This PR aims to fix atmosphere-ocean flux calculation on agrid. It also adds couple of missing check for the ESMF calls.
CMEPS Issues Fixed (include github issue #): https://github.com/ESCOMP/CMEPS/issues/270
No, bfb
No
- machines:
- description:
Testing …

fix aoflux calculation on agrid and add missing error checks

---

cesm/nuopc_cap_share/seq_drydep_mod.F90

initialize drydep_nflds to 0 in seq_drydep_readnl.
Issue found when running CAM test **ERP_Ln9_Vnuopc.ne5pg3_ne5pg3_mg37.QPC6.izumi_nag.cam-outfrq9s_clubbmf** with the nuopc driver. Got the following error (and preceding log message):
> [0] (seq_drydep_init) Number of dry deposition fields transfered is **
================================================================================
> =   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
> =   PID 117892 RUNNING AT i042.cgd.ucar.edu
> =   EXIT CODE: 9
> =   CLEANING UP REMAINING PROCESSES
> =   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
Contributors other than yourself, if any: N/A
CMEPS Issues Fixed (include github issue #): resolves #272
Are changes expected to change answers? (specify if bfb, different at roundoff, more …

initialize drydep_nflds to 0

---

cime_config/buildexe
cime_config/config_component.xml

Adds support for the crayenv container on cheyenne.  Please see https://github.com/ESCOMP/CESM/wiki/Using-CESM-in-the-Cray-environment-container-on-Cheyenne for usage details.
- machines:
- description: …

add_container_support

---

cime_config/buildexe

Correct replacement of MODEL with COMP_NAME in buildexe.
Fixes #281
- machines: cheyenne 
- details (e.g. failed tests):  Build case SMS_D.f09_t061.B1850MOM.cheyenne_intel
- description: …

correct COMP_NAME (was CIME_COMP)

---

cime_config/buildnml

Use comparisons of Mesh file instead of grid to determine if components are on the same grid.
This was done so that vertical component used in grid name does not affect this test.  
CMEPS Issues Fixed: #284 
- machines:
- description:
Testing …

use mesh file instead of grid name

---

cesm/driver/esm.F90
cime_config/namelist_definition_drv.xml

fixes to get can CAM single column SCT test to pass
The problem found in the CAM single column tests is that the nearest neighbor lats and lons need to come in from the same mesh file that CAM uses and not the lnd domain file which specifies the land mask. This PR accomplishes this.
This PR must also be accompanied by a CAM and CICE PR that turns off weight correction factors when all of the components share the same mesh file.
Are changes expected to change answers? (specify if bfb, different at roundoff, more substantial) bfb 
The following test now passes: SCT_D_Ln7_Vnuopc.T42_T42_mg17.QPC5.cheyenne_intel.cam-scm_prep
Testing uses the following …

fixes to CAM get can single column SCT test to pass

---

cime_config/buildnml

Correct the name of the drv log file in nuopc.runconfig
- machines:
- description:
- description: …

fix name of driver log

---

cesm/flux_atmocn/shr_flux_mod.F90
cime_config/namelist_definition_drv.xml
mediator/esmFldsExchange_cesm_mod.F90
mediator/med_phases_aofluxes_mod.F90

CESM specific - activated atm/ocn flux scheme2
Previously, the atm/ocn flux scheme2 did not have a hook for activation. This PR creates that hook. 
Meg Fowler carried out a one year run with scheme2 active, but I think things are looking reasonable.
Contributors other than yourself, if any: Meg Fowler
Any User Interface Changes (namelist or namelist defaults changes)? Yes - for CESM a new namelist flag for the atm/ocn flux scheme was introduced-  `ocn_surface_flux_scheme`. By default this is set to 0.
- ran ERS_Ld7.f19_g17.B1850.cheyenne_intel.allactive-defaultio and verified that it was bfb with cesm2_3_alpha09c
- …

CESM specific - activated atm/ocn flux scheme2

---

cesm/driver/esm.F90
cesm/nuopc_cap_share/driver_pio_mod.F90
cesm/nuopc_cap_share/init_pio_mod.F90
cesm/nuopc_cap_share/nuopc_shr_methods.F90

Extract the non-initialization parts of shr_pio_mod to a module in the
share repository, just keeping the initialization parts here.
This is part of a set of changes where I am splitting shr_pio_mod into two pieces: 
(1) Reading configuration files and initializing PIO appropriately
(2) Storing information about PIO (io system descriptors, io types, io formats) and providing an interface to query this information
Piece (2) lives in the share code and is used regardless of the driver. Piece (1) is driver-specific, so for now we have three versions of that piece: one in CMEPS (created by extracting the initialization pieces from `cmeps/cesm/nuopc_cap_share/shr_pio_mod.F90`), one in the cpl7 repo (created by extracting the initialization pieces from `share/src/shr_pio_mod.F90`), and one in …

Extract non-initialization parts of shr_pio_mod to a module in share

---

cime_config/buildnml

Setting wavice_coupling flag to true causes instabilities in WW3DEV in ERS_D tests. This PR sets this flag to false by default. (It may still be set to true manually). It will be set to true by default again when the underlying issue is identified and resolved.
Any User Interface Changes (namelist or namelist defaults changes)? none
ERS_D.TL319_t061_wt061.GMOM_JRA_WD.cheyenne_intel
ERS_D.TL319_t061_wt061.GMOM_JRA_WD.cheyenne_gnu
- machines:
2.3 alpha09c

Turn off wavice_coupling (temporary)

---

cime_config/buildnml

fix hard-wiring of wavice_coupling config (applies only to CESM)
This PR has a simple fix (changes nmlgen.set_value to nmlgen.add_default) in order to permit the 
setting of wavice_coupling to be changed in user_nl_cpl.
Verified that wavice_coupling could be changed in nuopc.runconfig my changing user_nl_cpl.
- description:
- description: …

fix hard-wiring of wavice_coupling config (applies only to CESM)

---

cesm/driver/esm_time_mod.F90
cime_config/buildnml
cime_config/config_component.xml
cime_config/config_component_cesm.xml
cime_config/namelist_definition_drv.xml

simplify specification of stop_option, rest_option and hist_option
This PR addresses issue #311 
Only the following values are now allowed
`none,never,nsteps,nseconds,nminutes,nhours,ndays,nmonths,nyears,date,end`
CMEPS Issues Fixed: #311 
Any User Interface Changes (namelist or namelist defaults changes)? None
Verified that SMS_Ln9.f19_g17.A.cheyenne_intel if HIST_OPTION is 'nstep', preview_namelist_fails
- tag: cesm2_3_beta09

simplify specification of stop_option, rest_option and history_option (cesm only)

---

cesm/driver/esm_time_mod.F90
cesm/nuopc_cap_share/shr_drydep_mod.F90
mediator/med_time_mod.F90

Replace shr_mpi_bcast with ESMF_VMBroadcast.   Was not working when lndroot .ne. atmroot.
This change affects cesm only.
Contributors other than yourself, if any: Mariana
Are changes expected to change answers?  bfb
- machines:
- machines and compilers: cheyenne, intel 
- machines and compilers Testnames: ['ERS.ne30_g17.B1850.cheyenne_intel',   'ERS_Ln9.f19_f19_mg17.FHIST.cheyenne_intel.cam-outfrq9s']
- details (e.g. failed tests): ALL PASS
- description:
- …

was not working when atm and lnd did not share all tasks

---

cesm/nuopc_cap_share/driver_pio_mod.F90

With ESMF_AWARE_THREADING=TRUE not all active tasks are using PIO, this causes a deadlock without this change. 
- machines:
- description:
- description:
- …

needed for using ESMF_AWARE_THREADING=TRUE

---

cesm/driver/ensemble_driver.F90
cesm/driver/esm.F90
cesm/nuopc_cap_share/driver_pio_mod.F90
cesm/nuopc_cap_share/nuopc_shr_methods.F90
cesm/nuopc_cap_share/shr_carma_mod.F90
cesm/nuopc_cap_share/shr_drydep_mod.F90
cesm/nuopc_cap_share/shr_megan_mod.F90
cesm/nuopc_cap_share/shr_ndep_mod.F90
cesm/nuopc_cap_share/shr_ozone_coupling_mod.F90
cime_config/namelist_definition_drv.xml

Clean up usage of log files
Depricated shr_file_getLogUnit and added shr_log_getLogUnit
Depends on https://github.com/ESCOMP/CESM_share/pull/36
- machines:
- machines and compilers cheyenne intel
- details (e.g. failed tests): all consistant with baselines. 
- description: …

move shr_file_getLogUnit to shr_log_getLogUnit

---

cesm/driver/ensemble_driver.F90

Remove a performance funnel in ensemble_driver which caused linear scaling with number of members
CMEPS Issues Fixed (include github issue #): Fixes #326
- machines:
- description:
- description:
- …

fix issue with scaling over instances

---

cime_config/config_component_cesm.xml

Fix documentation of default value of DOUT_S_SAVE_INTERIM_RESTART_FILES, as pointed out in https://bb.cgd.ucar.edu/cesm/threads/restart-files-were-deleted-when-archiving-after-the-run-was-completed.7885/
Contributors other than yourself, if any: none
Are changes expected to change answers? (specify if bfb, different at roundoff, more substantial)  NO
Any User Interface Changes (namelist or namelist defaults changes)? no
No testing performed.
- machines:
Testing performed if application target is …

Fix documentation of DOUT_S_SAVE_INTERIM_RESTART_FILES

---

.pre-commit-config.yaml
cime_config/buildnml

Multi_driver is always True for cmeps, no need for logic here.  
- machines:
- description:
- description:
- repository to …

remove multi_driver, add precommit config file

---

.github/workflows/extbuild.yml
.github/workflows/srt.yml

Updates the github workflow to use reusable actions
- machines:
- description:
- description: …

update workflow to use actions from cdeps

---

cesm/nuopc_cap_share/shr_expr_parser_mod.F90
cesm/nuopc_cap_share/shr_megan_mod.F90

Adds the capability to split up long specifier string in the namelist into multiple lines.  
Also provides the capability to specify common coefficients to multiple MEGAN terms like this:
```
... + a*(A + B + C +... ) +...
```
bfb -- no changes to answers
ERP_Ln9_Vnuopc.f09_f09_mg17.FC2000climo.cheyenne_intel.cam-outfrq3s_sums (Overall: PASS) details:
ERP_Ln9_Vnuopc.ne30_ne30_mg17.FCnudged.cheyenne_intel.cam-outfrq9s (Overall: PASS) details:
SMS_D_Ln9_Vnuopc.f09_f09_mg17.FC2000climo.cheyenne_intel.cam-outfrq3s_sums (Overall: PASS) details: …

Updates to the MEGAN specifier string parser

---

cesm/driver/ensemble_driver.F90
cesm/driver/esm.F90
cesm/nuopc_cap_share/driver_pio_mod.F90

The aysncio pr accidently regressed the recent fix for multiinstance cases, this fixes it.  
Depends on cime #4359
- machines:
- machines and compilers SMS_C80_P108x1_Lh1_Vnuopc.f09_f09_mg17.FHIST_DARTC6.cheyenne_intel.cam-dartcambigens ERS_C3_Vnuopc.f19_g17.A.cheyenne_intel.drv-asyncio1pernode, …

fix the multi instance initialization

---

cime_config/config_component_cesm.xml
cime_config/namelist_definition_drv.xml
cime_config/runseq/driver_config.py
cime_config/runseq/runseq_general.py
mediator/med_phases_prep_ocn_mod.F90

changes needed for CDEPS PR #213
Changes needed to enable flexible import to data ocean to be available in mediator history files
CMEPS Issues Fixed (include github issue): #340 
Are changes expected to change answers? (specify if bfb, different at roundoff, more substantial) No - bfb
Any User Interface Changes (namelist or namelist defaults changes)? None
Verified bfb for docn test cases.
Verified that SMS_Ld5.f09_g17.B1850G.cheyenne_intel.allactive-cism-test_coupling and 
ERP_Ln9_Vnuopc.ne30_ne30_mg17.F2000climo.cheyenne_intel.cam-outfrq9s were bfb compared to cesm2_3_beta11
- cesm2_3_beta11

changes needed for CDEPS PR #213

---

cime_config/namelist_definition_drv.xml

xgrid was causing restart problems; revert this until we can solve those problems
Contributors other than yourself, if any: Testing from @fischer-ncar , consultation with @jedwards4b 
Are changes expected to change answers? (specify if bfb, different at roundoff, more substantial) Yes - answer changes for cases that compute atm-ocn fluxes
**No testing done exactly on this branch, but @fischer-ncar did testing with both cmeps0.14.16 and cmeps0.14.14 (note that cmeps0.14.14 was the tag that appeared before cmeps0.14.16 due to an oddity in tag ordering); this tag is a blend of those two.
- machines: …

Revert default aoflux_grid to ogrid

---

mediator/med_io_mod.F90

fieldNameList is not always allocated, so this deallocate caused problems in some circumstances. We could wrap the deallocate in a conditional, but since allocatable arrays are automatically deallocated upon leaving a subroutine, this deallocate statement is unnecessary.
Contributors other than yourself, if any: @olyson found this issue
Are changes expected to change answers? (specify if bfb, different at roundoff, more substantial) NO
Any User Interface Changes (namelist or namelist defaults changes)? none
NONE
- machines:
- …

Remove unnecessary deallocate

---

cime_config/testdefs/testlist_drv.xml

Fix typo in testlist - aux_cam should be aux_cmeps
Fixes #357 
- machines:
- description:
- description:
- repository to …

replace aux_cam with aux_cmeps in testlist

---

cime_config/buildexe

Addition of an option to pass flags needed to link external libraries for use in CAM.
none (This is my first PR to this repo, so apologies if this is not the right way to suggest this change)
#355
No (bfb)
No
- machines:
- description:
- …

add CAM linked lbs to exe build

---

mediator/med_phases_aofluxes_mod.F90

Adds optional flags to ESMF_FieldRegridStore command to make xgrid reproducable.
Contributors other than yourself, if any: mvertens, esmf team
CMEPS Issues Fixed (include github issue #): 
- machines: cheyenne
- machines and compilers cheyenne intel
- details:  
The following tests were all rerun on the xgrid and now all PASS
- ERP_D_Ln9_Vnuopc.f19_f19_mg17.FSD.cheyenne_intel.cam-outfrq9s_sd 
- …

fix issue with xgrid reproducibility

---

cesm/nuopc_cap_share/shr_lightning_coupling_mod.F90
cime_config/namelist_definition_drv_flds.xml
mediator/esmFldsExchange_cesm_mod.F90
mediator/fd_cesm.yaml

Enables passing prognostic cloud-to-ground lightning flash frequency from CAM to CTSM
Issues Fixed (include github issue #):
https://github.com/ESCOMP/CTSM/issues/1630 
https://github.com/ESCOMP/CAM/issues/567
b4b
ERC_D_Ln9_Vnuopc.f19_f19_mg17.QPC6.cheyenne_intel.cam-outfrq3s_cosp 
SMS_D_Ln9_Vnuopc.f19_f19_mg17.FWma2000climo.cheyenne_intel.cam-outfrq9s
SMS_D_Ln9_Vnuopc_P720x1.ne30pg3_ne30pg3_mg17.FCLTHIST.cheyenne_intel.cam-outfrq9s 
SMS_Ln9_Vnuopc.f19_f19.F2000climo.cheyenne_intel.cam-silhs

Cloud-to-ground lightning flash frequency coupling

---

cesm/driver/ensemble_driver.F90

, not used in cesm this is a memory and intialization time saver
Turn off the initialization Hierarchy protocol used in esmf. This decreases memory usage and initialization time and is particularly noticeable at scale.
- machines:
- …

turn off HierarchyProtocol

---

cesm/driver/esm.F90
mediator/med_diag_mod.F90

Improve the salt diags, including more significant digits. 
Tested using  SMS.ne30pg3_t061.B1850MOM.cheyenne_intel
Contributors other than yourself, if any: Gustavo
CMEPS Issues Fixed #367 
- machines:
- description:
- description:
- details …

Improve diag salt format

---

mediator/med_diag_mod.F90
mediator/med_methods_mod.F90
mediator/med_phases_prep_atm_mod.F90
mediator/med_phases_prep_glc_mod.F90
mediator/med_phases_prep_ice_mod.F90
mediator/med_phases_prep_lnd_mod.F90
mediator/med_phases_prep_ocn_mod.F90
mediator/med_phases_prep_rof_mod.F90
mediator/med_phases_prep_wav_mod.F90

checking of nans in export field bundles #377
Introduced a new method med_methods_FB_check_for_nans in med_methods_mod and has all of the med_phases_prep_xxx_mod.F90 files call this method. If Nans are found in any field the model will abort, but it will first print out the number of nans found for each field and on each processor.
Contributors other than yourself, if any: @jedwards4b 
CMEPS Issues Fixed: #370 
Are changes expected to change answers?  bfb
Any User Interface Changes (namelist or namelist defaults changes)? None
Verified that if nans were set in the 1d and 2d field in the call to med_phases_prep_atm, then PET files were written with the right statistics and the model aborted.

checking of nans in export field bundles

---

mediator/med_methods_mod.F90

Recent PR #377 had an error that causes it to be a no-op.
Replace CESM_COUPLED with CESMCOUPLED, replace shr_infan_isfan with shr_infnan_isnan

CESM_COUPLED should be CESMCOUPLED

---

cime_config/namelist_definition_drv.xml
mediator/med_phases_prep_ocn_mod.F90

…mom ocn
Critical bug fixes.   First the aoflux should happen on the xgrid,
second the Mom ocn model uses sw bands and not swnet, change the
test in prep_ocn to work with MOM. 

make xgrid default and fix sw flux to mom ocn

---

.github/workflows/extbuild.yml
cime_config/namelist_definition_drv.xml
mediator/med.F90
mediator/med_methods_mod.F90
mediator/med_phases_prep_atm_mod.F90
mediator/med_phases_prep_glc_mod.F90
mediator/med_phases_prep_ice_mod.F90
mediator/med_phases_prep_lnd_mod.F90
mediator/med_phases_prep_ocn_mod.F90
mediator/med_phases_prep_rof_mod.F90
mediator/med_phases_prep_wav_mod.F90

Add check_for_nans to the nuopc.runconfig 
Contributors other than yourself, if any: 
CMEPS Issues Fixed: #384
Are changes expected to change answers? (specify if bfb, different at roundoff, more substantial)  BFB
Any User Interface Changes (namelist or namelist defaults changes)?  Add
logical variable check_for_nans modifiable in user_nl_cpl.
Tested using cesm2_3_alpha13b
PFS.ne30pg3_t061.B1850MOM.cheyenne_intel.allactive-defaultio

Add check for nans config option

---

cime_config/namelist_definition_drv.xml

testing indicates we are not yet ready for xgrid

---

mediator/med_methods_mod.F90

If both lranki and lranko are 0 this is not an error.
CMEPS Issues Fixes #390 
Problem was found when running  PFS.ne30pg3_t232.BLT1850_v0c.derecho_intel at high task counts (5888 tasks)

both =0 is not an error

---

.github/workflows/srt.yml
mediator/esmFldsExchange_cesm_mod.F90
mediator/med_internalstate_mod.F90
mediator/med_map_mod.F90

Fixes the x case by ignoring the rof->ocn coupling in med_internalstate_mod.F90
CMEPS Issues Fixed #396 

fix the x case

---

mediator/med_phases_ocnalb_mod.F90

Added a field length to the L field descriptor.
The nag compiler didn't like have a naked L field descriptor.
BFB
None
ERR.f45_g37_rx1.A.izumi_nag build

Add length to logic format descriptor, needed for nag.

---

cesm/flux_atmocn/shr_flux_mod.F90

Add rollover of surface fluxes at high wind speed.  
Contributors other than yourself, if any: [zarzycki](https://github.com/zarzycki)
CMEPS Issues Fixed: #393 
Are changes expected to change answers? possibly more substantial
Any User Interface Changes (namelist or namelist defaults changes)? NO

add surface flux rollover

---

cime_config/config_component.xml
cime_config/namelist_definition_drv.xml

Remove unused ESMF_LOGFILE_KIND variable.
This variable is not used, control for esmf logfiles is through variable
CREATE_ESMF_PET_FILES
Contributors other than yourself, if any: Ufuk
CMEPS Issues Fixed #416 
Are changes expected to change answers? (specify if bfb, different at roundoff, more substantial)  bfbSMS.f19_g17.X.frontera_intel
SMS.f19_g17.X.frontera_intel

remove this unused variable

---

doc/source/addendum/req_attributes.rst
doc/source/esmflds.rst
doc/source/generic.rst
doc/source/introduction.rst
doc/source/prep.rst
mediator/CMakeLists.txt
mediator/ESMFConvenienceMacros.h
mediator/ESMFVersionDefine.h
mediator/Makefile
mediator/esmFldsExchange_ufs_mod.F90
mediator/med.F90
mediator/med_fraction_mod.F90
mediator/med_internalstate_mod.F90
mediator/med_map_mod.F90
mediator/med_phases_aofluxes_mod.F90
mediator/med_phases_prep_atm_mod.F90

Includes changes recently committed to https://github.com/NOAA-EMC/CMEPS
The non-CESM coupling modes have been clarified and renamed to use "ufs" instead of "nems". 
The ``esmFldsExchange_nems_mod`` has be renamed to ``esmFields_Exchange_ufs_mod``
Documentation has been updated.
- fixes https://github.com/NOAA-EMC/CMEPS/issues/100
- fixes https://github.com/ufs-community/ufs-weather-model/issues/1756
- All changes should be B4B for CESM
- no
If possible, please also …

Rename ufs related coupling modes; replace nems with ufs

---

cime_config/config_component.xml

Removes SMP_PRESENT from xml  
Requires cime PR https://github.com/ESMCI/cime/pull/4546
Are changes expected to change answers? no bfb

remove the SMP_PRESENT variable and replace with BUILD_THREADED

---

cime_config/buildnml
cime_config/namelist_definition_drv.xml

Turn on gust by default for cam%dev compsets.

turn add_gusts on by default for camdev

---

cime_config/runseq/runseq_TG.py

This makes the logic for running GLC consistent with runseq_general.py. This change is relevant for the unusual case where a T compset (CISM forced by dlnd) is being run with CISM in noevolve mode: in this case, we don't want to run CISM, and trying to run CISM leads to incorrect behavior in a restart case (which is how this issue was detected).
With this change,
ERS_D_Ly3.f09_g17_gris4.T1850Gg.derecho_intel.cism-noevolve passes.
Contributors other than yourself, if any: @Katetc 
Are changes expected to change answers? No - bfb (except for the unusual case of a T compset with noevolve CISM)
ERS_D_Ly3.f09_g17_gris4.T1850Gg.derecho_intel.cism-noevolve
Using …

For T compsets, only run GLC if med_to_glc is true

---

.github/workflows/srt.yml
cime_config/config_component.xml
cime_config/namelist_definition_drv.xml
mediator/esmFldsExchange_cesm_mod.F90
mediator/esmFldsExchange_hafs_mod.F90
mediator/esmFldsExchange_nems_mod.F90
mediator/esmFldsExchange_ufs_mod.F90
mediator/med.F90
mediator/med_fraction_mod.F90
mediator/med_internalstate_mod.F90
mediator/med_io_mod.F90
mediator/med_map_mod.F90
mediator/med_methods_mod.F90
mediator/med_phases_aofluxes_mod.F90
mediator/med_phases_cdeps_mod.F90
mediator/med_phases_history_mod.F90
mediator/med_phases_ocnalb_mod.F90
mediator/med_phases_post_atm_mod.F90
mediator/med_phases_prep_atm_mod.F90
mediator/med_phases_prep_ocn_mod.F90
mediator/med_phases_prep_wav_mod.F90

This PR aims to bring CDEPS inline capability to CMEPS to fill unmapped regions for the regional modeling configurations. More information can be found in the following presentation: https://docs.google.com/presentation/d/1Tk76zlsRiT7_KMJiZsEJHNvlHciZJJBBhsJurRMxVy4/edit#slide=id.g2613ed2f8f8_0_0
This PR is also linked to complete the implementation: https://github.com/ESCOMP/CDEPS/pull/259
Contributors other than yourself, if any: @danrosen25 @binli2337 @BinLiu-NOAA 
CMEPS Issues Fixed (include github issue #): No
Are changes expected to change answers? (specify if bfb, different at roundoff, more substantial) No
Any User Interface Changes (namelist or namelist defaults changes)? No. 
The user need to add new phase (`med_phases_cdeps_run`) to the run sequence to activate the feature. …

CMEPS PR for CDEPS Inline implementation

---

cesm/driver/esm.F90

Add code to find unstructured column closest to Single Column Model specified lat/lon.
Contributors other than yourself, if any: NA
CMEPS Issues Fixed (include github issue #): NA
BFB for Eulerian grid (same code).  New functionality to parse unstructured grid.
Any User Interface Changes (namelist or namelist defaults changes)? NA
Passing aux_cam regression suite on Derecho(Intel) and Izumi(nag and gnu)

Add unstructured grid support for use with new Spectral Elements SCAM

---

cesm/flux_atmocn/shr_flux_mod.F90
mediator/esmFldsExchange_cesm_mod.F90
mediator/fd_cesm.yaml
mediator/med_phases_aofluxes_mod.F90

This PR revises the definition of U10 to be only the large-scale resolved winds, as was the case before gusts were added to CMEPS/CAM. The merged U10 (large-scale + gusts) is now output as a separate variable. 
Note that duu10n is still reflective of the merged U10, as this is the wind speed used to compute actual surface fluxes. But the U10 that's output is back to being un-merged. 
Contributors other than yourself, if any: 
Credit to @quantheory for pointing out the issue and developing a fix for E3SM here https://github.com/E3SM-Project/E3SM/commit/5813d4103bafda50840c7df8f87296872627f19c
CMEPS Issues Fixed (include github issue #): 
https://github.com/ESCOMP/CMEPS/issues/438 
Are changes expected to change answers? (specify if bfb, different at roundoff, more substantial)
The change …

Update U10 to be resolved wind; add variable for U10+gusts

---

mediator/med_phases_profile_mod.F90

There was an issue with running on leap day.
Need to use Gregorian Clock for computing wallclockTime

fix leap day issue

---

cime_config/buildexe

Fixes an issue when running create_test with a full compset name that contains special characters like %.
I changed the call to the Makefile from buildexe to use a relative path instead of full path, this seems to 
have addressed the issue.
CMEPS Issues Fixed (include github issue #): 

fixes an issue with symbols in compset names on derecho

---

mediator/med_phases_history_mod.F90
mediator/med_phases_prep_glc_mod.F90

In order to evaluate coupled CESM runs with no active ice sheets, it is very helpful to output the glacier forcing fields from the coupler on the glacier grid. @mvertens wrote this update to CMEPS to support exporting state to glc, added into the lnd2glc auxiliary file.
Contributors other than yourself, if any: @mvertens 
bfb with added fields in the glc cpl hist files.
I tested this with various configurations and grids. The output looked …

Output downscaled glacier data in cpl glc hist file

---

cime_config/config_component_cesm.xml
cime_config/namelist_definition_drv.xml
cime_config/runseq/driver_config.py
cime_config/runseq/runseq_general.py
mediator/esmFldsExchange_cesm_mod.F90
mediator/fd_cesm.yaml
mediator/med_phases_profile_mod.F90

Updates for adding a cdeps dglc component
CMEPS Issues Fixed:  None
Are changes expected to change answers? bfb 
Any User Interface Changes: Only if are using the new dglc component, otherwise no.
The testing was done with the new dglc component on derecho.
The changes should not effect any other existing CESM configuration.
I can run a separate test suite if needed.

Changes for the addition of a new dglc component 

---

cime_config/runseq/driver_config.py
cime_config/runseq/runseq_TG.py
cime_config/runseq/runseq_general.py

Previously we hadn't been doing the mapping from MED -> GLC when CISM was running in NOEVOLVE mode. This was a problem because this downscaled SMB is one of the main benefits of running CISM in NOEVOLVE mode.
Resolves ESCOMP/CMEPS#426. See that issue for details.
Contributors other than yourself, if any: Consultation with @mvertens 
CMEPS Issues Fixed (include github issue #): #426 
Are changes expected to change answers? Changes answers for some cpl hist fields (diagnostic only) in configurations with CISM in NOEVOLVE mode. Otherwise bit-for-bit.
I have verified that the run sequence is the same as before for cases with CISM in EVOLVE mode, as well as for cases with sglc or xglc. Differences just appear in cases with …

Run MED -> GLC in CISM NOEVOLVE mode

---

cime_config/buildnml

One line change so that ww3dev can be renamed ww3 

renames ww3dev to ww3

---

mediator/med.F90
mediator/med_phases_restart_mod.F90

This loop in med_phases_restart_mod.F90 was causing integer overflow because the med component should not be included.   This was only happening with the nag compiler in debug mode and would not normally be a problem since integer overflows are ignored (except by nag in debug mode) and the resulting values were never used.  

avoid integer overflow by skipping mediator in restart loop

---

.github/workflows/srt.yml

Reverts ESCOMP/CMEPS#464  This wasn't needed and should not have been merged.

Revert "test github testing in cime PR #4631"

---

cime_config/buildnml

Change `CAM%DEV` to `CAM70` in buildnml
This change needs to be coordinated with the upcoming CAM tag which changes the physics package descriptor `cam_dev` to `cam7`.  Concurrently the compset token `CAM%DEV` is changing to `CAM70`.  The CMEPS buildnml script has a hardcoded `CAM%DEV` token which must be changed to `CAM70` for consistency.

Change CAM%DEV to CAM70 in buildnml

---

cime_config/namelist_definition_drv.xml
mediator/med.F90
mediator/med_phases_post_rof_mod.F90

Remove negative runoff before mapping rof -> ocn by setting negative runoff to 0 and downweighting all positive runoff appropriately so that the global runoff sum is the same as before.
Contributors other than yourself, if any: @mvertens 
- Resolves #405 
Are changes expected to change answers? (specify if bfb, different at roundoff, more substantial) : **Yes - changes answers substantially for runoff fields in B compsets (or other configurations with both active land/river and active ocean) (appears not to change answers in most / all other configurations)**
Any User Interface Changes (namelist or namelist defaults changes)? New namelist item: remove_negative_runoff (true by default)
Tested in the context of cesm2_3_beta17
Ran a number of …

Remove negative runoff

---

.github/workflows/srt.yml
cesm/nuopc_cap_share/seq_drydep_mod.F90
mediator/med_phases_aofluxes_mod.F90

The associated statement won't work because the association is done in the called subroutine. 

new fix for add_gusts

---

cesm/nuopc_cap_share/seq_drydep_mod.F90
mediator/med_fraction_mod.F90

bug fix primarily for usf testing

---

mediator/med_phases_aofluxes_mod.F90

Add an allocate for the rainc variable which is only use if add_gusts is enabled.

gnu reports an error if this unused variable is not allocated

---

mediator/med_io_mod.F90

Add a check to make sure variables are allocated before deallocating
This came up when Cecile was trying to write a restart with the BMT compset.

make sure variables are allocated before deallocating

---

mediator/med_phases_aofluxes_mod.F90

The variable So_ugustOut was set twice due to a merge error.

fix an error in the aoflux wind_gust fields

---

mediator/esmFldsExchange_cesm_mod.F90
mediator/fd_cesm.yaml
mediator/med_diag_mod.F90
mediator/med_phases_prep_atm_mod.F90
mediator/med_phases_prep_ocn_mod.F90

Addition of glc runoff enthalpy fluxes in CESM.
The recent separation of river runoff (`rofi` and `rofl`) and land ice runoff (`rofi_glc` and `rofl_glc`) requires calculating and exporting the heat content associated with glc runoffs from the mediator to the ocean. This pull request introduces the following fluxes to address this requirement: `Foxx_hrofl_glc` and `Foxx_hrofi_glc`. However, because river runoff (rof) and land ice runoff are still merged in the mediator, these new fluxes are currently computed and exported as 0.0. Once the runoff fields are fully separated, these fluxes should be validated to ensure they are computed accurately.
https://github.com/NCAR/MOM6/issues/281
Are changes expected to change answers? (specify if bfb, …

Compute and export heat content associated with glc runoffs

---

mediator/med_methods_mod.F90
mediator/med_phases_prep_ocn_mod.F90

Skip nan test in med_phases_prep_ocn_mod.F90 on first pass.   This is to avoid detecting nan's in the as yet undefined pslv field passed from atm.
The test that found this error was SMS_D_Ld2.ne30pg3_t232.BMT1850.derecho_gnu.allactive-defaultio
in cesm3_0_beta02.  I first tried to make the change in atm_import_export.F90 in the cam nuopc interface code, but that didn't seem to work.

nan was picked up in pslv field on first pass

---

cime_config/config_component.xml

This just changes the default PIO_NETCDF_FORMAT for all components to 64bit_data.  This is needed for ultra-high resolution runs, but shouldn't adversely impact standard runs either other than needing a tiny bit more space.
@jedwards4b 
#491
BFB; this only impacts output formats.
No
No systematic testing yet, though we've run this way for multiple cases (mostly atmosphere+land) for a while.

Changes the default PIO format from 64bit_offset to 64bit_data

---

cime_config/config_component.xml

Adds CASE_GIT_REPOSITORY variable in support of https://github.com/ESMCI/cime/pull/4655

add CASE_GIT_REPOSITORY variable

---

cime_config/buildnml
cime_config/namelist_definition_drv.xml
doc/source/addendum/req_attributes_cesm.rst
mediator/med_phases_prep_glc_mod.F90

Remove the glc_renormalize_smb option on_if_glc_coupled_fluxes. This had been the default. Change the default to 'on'. This maintains consistent behavior between different configurations.
CMEPS Issues Fixed (include github issue #): Resolves ESCOMP/CMEPS#133
Are changes expected to change answers? YES: changes answers by greater than roundoff for T compsets (active GLC with DLND) (now SMB is remapped with renormalization for T compsets by default); answers should be bit-for-bit in all other configurations (unless there is some configuration/combination that I'm not thinking of...)
Any User Interface Changes (namelist or namelist defaults changes)? Removes `on_if_glc_coupled_fluxes` option to `glc_renormalize_smb`
Please describe the tests along …

Simplify logic for glc_renormalize_smb

---

cime_config/runseq/driver_config.py

fix problem with no coupler file written at restart interval
In the following test ERP_Ln9.ne30pg3_ne30pg3_mtn14.NF1850.betzy_intel.cam-outfrq9
where the compset is 1850_CAM%DEV%LT%NORESM%CAMoslo_CLM51%SP_CICE%PRES_DOCN%DOM_MOSART_DGLC%NOEVOLVE_SWAV_SESP
the glc coupling interval is forced to be the atm coupling interval (i.e. 48) but at the same time the run sequence is forced to be that glc is only called at the end of the run sequence. With this fix - the forcing is removed and there is no longer a descrepancy between the glc coupling interval and the run sequence. This now fixes the ERP test where the compset has DGLC%NOEVOLVE.
CMEPS Issues Fixed: 
Are changes expected to change answers? should be bfb
Any User Interface Changes (namelist …

fix problem with no coupler file written at restart interval

---

mediator/esmFldsExchange_cesm_mod.F90

Runs with `aoflux_grid = "xgrid"` and `add_gusts = .false.` have been failing with:
```
20240903 141813.539 ERROR            PET003 ESMCI_Container.h:178 ESMCI::Container::get() Invalid argument  - key does not exist: So_ugustOut
```
This PR fixes this issue by avoiding adding the two new gust fields to the list of mediator fields if add_gusts is false.
The explanation for why this caused an issue with the exchange grid is:
- In `mediator/esmFldsExchange_cesm_mod.F90`: `esmFldsExchange_cesm`, `So_ugustOut` and `So_u10withGust` are added as atmosphere-ocean fluxes regardless of the value of `add_gusts`. 
- But in `mediator/med_phases_aofluxes_mod.F90`: `set_aoflux_out_pointers`, the `fldbun_getfldptr` call is only made if `add_gusts` is true.
- There is a difference in behavior with xgrid …

Fix for exchange grid with add_gusts false: Only add gust fields if add_gusts is true

---

mediator/med_phases_aofluxes_mod.F90

Use srcTermProcessing=0 for all xgrid FieldRegridStore calls.
This is needed for bit-for-bit reproducibility. Most of the calls to FieldRegridStore weren't setting srcTermProcessing at all; this can lead to irreproducibility of the results. Two of the calls had srcTermProcessing set to 1 before, which leads to reproducibility but (according to Gerhard Theurich) is often worse for performance than a value of 0.
Note that we use a value of 0 in the calls in med_map_mod.
Contributors other than yourself, if any: Guidance from @oehmke and @theurich
CMEPS Issues Fixed (include github issue #): Resolves #505 
Are changes expected to change answers? YES: roundoff-level differences expected for runs with `aoflux_grid = "xgrid"` (but those runs had expected roundoff-level differences from run to …

Fix xgrid reproducibility by using srcTermProcessing=0 for all xgrid FieldRegridStore calls

---

cime_config/buildnml
cime_config/config_component.xml
cime_config/namelist_definition_drv.xml
mediator/esmFldsExchange_cesm_mod.F90

Reintroduce wav2ocn and ocn2wav map xml variables.

wav2ocn and ocn2wav maps are still needed in some cases

---

cime_config/namelist_definition_drv.xml

buildnml was setting variable samegrid_wav_ocn but namelist_definintion_drv.xml was looking for samegrid_ocn_wav

variable name mismatch

---

cime_config/config_component.xml

As discussed in https://github.com/ESMCI/cime/pull/4687, it is better remove the GPU options from the Python workflow in CIME and use XML files instead to configure them for CESM.
This PR introduces the necessary changes to accomplish this goal.
It should work together with the following PRs:
- CIME: https://github.com/ESMCI/cime/pull/4690
- ccs_config_cesm: https://github.com/ESMCI/ccs_config_cesm/pull/189

Update XML variables for GPU configurations

---

mediator/med_phases_aofluxes_mod.F90

Fix the logic for adding psfc to aoflux_in, particularly needed for cases using the exchange grid.
This is needed to avoid a segmentation fault in the call to flux_atmocn in SMS_Ld2.ne30pg3_t232.BMT1850.derecho_gnu.allactive-defaultio when running with aoflux_grid=xgrid. (This shows up when running with xgrid because the FB_fldchk can't be used in this situation - see details in my [comment below](https://github.com/ESCOMP/CMEPS/pull/514#issuecomment-2427645256).)
Are changes expected to change answers? No
SMS_Ld2.ne30pg3_t232.BMT1850.derecho_gnu.allactive-defaultio with aoflux_grid="xgrid", from cesm3_0_beta03
Also ran many other …

Fix logic for adding psfc to aoflux_in

---

cime_config/namelist_definition_drv.xml
cime_config/testdefs/testlist_drv.xml
cime_config/testdefs/testmods_dirs/drv/aoflux_ogrid/user_nl_cpl

Use the exchange grid for the atmosphere-ocean flux calculation unless atm & ocn are on the same grid.
Also adds a test of aoflux_grid=ogrid to the aux_cmeps test suite so that that configuration continues to be tested.
Contributors other than yourself, if any: Consultation with @mvertens on how we should set the default – specifically, continuing to use ogrid when atm & ocn are on the same grid.
- Resolves #502 
Are changes expected to change answers? YES - significant answer changes for any configuration where atmosphere-ocean flux calculations are performed and atm & ocn are on different grids.
Any User Interface Changes (namelist or namelist defaults changes)? Changes default value for aoflux_grid
Please describe the tests along with the …

Make xgrid the default aoflux_grid when atm and ocn are running on different grids

---

cime_config/config_component.xml

Adds variables MEM_PER_TASK and MAX_MEM_PER_NODE for greater control of memory options on derecho - it can also be used elsewhere but initially only on derecho, requires cime and ccs_config changes.

add memory usage variables for use on derecho

---

.github/workflows/srt.yml
cesm/driver/esm_time_mod.F90
cime_config/buildnml
cime_config/config_component.xml
cime_config/namelist_definition_drv.xml
mediator/med_diag_mod.F90
mediator/med_phases_restart_mod.F90

Add timestamp to rpointer files Done in a backward compatible manor.  
This depends on https://github.com/ESCOMP/CESM_share/pull/53

Add timestamp rpointer

---

mediator/med.F90
mediator/med_internalstate_mod.F90
mediator/med_map_mod.F90

Replaces the current implementation, which (optionally) allows the RH dststatus fields to be written to individual files (per dst component, per mapindex) on the internal mesh representation. This requires the user to manipulate the written fields in order to visualize them on the model domain. 
In this PR, if ``write_dststatus`` is true, a ``FBDdststatus`` is created for each destination component, containing all the mappings from ``n1`` to ``n2`` for that component and the dstatusfields are added to the component's FB. All the FBs are then written using med_io_write_FB using the cpl_scalars. 
Fixes https://github.com/NOAA-EMC/CMEPS/issues/127
Are changes expected to change answers? (specify if bfb, …

update retrieval and writing of dststatus fields

---

mediator/esmFldsExchange_cesm_mod.F90

We need mapbilinr_nstod for ice to wave fields. This is because some islands in the higher res domain are not in the low res wave domain.
These will change answers only when wave / ice coupling is active.

Update ice2wav maps

---

.github/workflows/extbuild.yml
cime_config/namelist_definition_drv.xml

ERI test and ERP test cannot have write_restart_at_endofrun 

restart at end of run needs to be false for these tests

---

cime_config/buildnml
mediator/med.F90
mediator/med_phases_restart_mod.F90

When using create_newcase without create_test TESTCASE will not be defined in the env files and will be set to None.  Change None to 'UNSET' so that xml interpolation works with this value.
Fixes #520
This was failing in run_neon under CTSM. With
``` shell
cd python
./run_sys_tests --sys
```
Which passes with this update

replace testcase None in config with unset

---

.github/workflows/extbuild.yml
cesm/driver/esm.F90
cesm/driver/esm_time_mod.F90
cesm/flux_atmocn/shr_flux_mod.F90
cesm/nuopc_cap_share/driver_pio_mod.F90
cesm/nuopc_cap_share/shr_drydep_mod.F90
mediator/esmFlds.F90
mediator/med.F90
mediator/med_diag_mod.F90
mediator/med_io_mod.F90
mediator/med_map_mod.F90
mediator/med_merge_mod.F90
mediator/med_methods_mod.F90
mediator/med_phases_aofluxes_mod.F90
mediator/med_phases_history_mod.F90
mediator/med_phases_ocnalb_mod.F90
mediator/med_phases_post_glc_mod.F90
mediator/med_phases_post_rof_mod.F90
mediator/med_phases_prep_glc_mod.F90
mediator/med_phases_prep_rof_mod.F90
mediator/med_phases_restart_mod.F90

Change of approach based on discussion in https://github.com/ESCOMP/CMEPS/discussions/534

Shr log error

---

cime_config/config_component.xml

A new variable named `RUN_POSTPROCESSING` has been added to `env_run.xml`. This variable will be `FALSE` by default, but setting it to `TRUE` will (eventually) run some postprocessing scripts as part of the default workflow. In that respect, its behavior will be similar to how `DOUT_S` controls the short-term archiver.
This is part of the CESM push to add [CUPiD](https://github.com/NCAR/CUPiD) to the CESM workflow. @rljacob asked that we keep the name generic (so this is not `RUN_CUPID_ANALYSIS` 😄), and the CUPiD team is definitely willing to change this to something else. It's not entirely clear that CMEPS is the best place to define this variable, as it stands it will show up in `env_case.xml` for all models using CMEPS but setting it to `TRUE` won't do anything in any of them except …

Add RUN_POSTPROCESSING variable to env_run.xml

---

cime_config/namelist_definition_drv.xml

Always default to ogrid when atm model is datm.

always set atmocn grid to ogrid with datm

---

mediator/med_internalstate_mod.F90
mediator/med_map_mod.F90
mediator/med_phases_ocnalb_mod.F90

Explicitly creates mappatch_uv3d, mapbilnr_uv3d. Adds a mapconsf_uv3d mapping for use by UFS.
- fixes #548 
- required by https://github.com/ufs-community/ufs-weather-model/issues/2667
This PR does not yet implement the mapping changes required by UFS and so is bfb in current develop branch of UFS. It should be B4B in CESM, but requires testing.

Add explicit RH creation for uv3d mapping

---

mediator/esmFldsExchange_cesm_mod.F90
mediator/med_diag_mod.F90

When @mvertens reworked the GLC -> OCN runoff mapping, she put in place hooks to keep the glc-derived runoff separate from the lnd-derived runoff. However, @gustavo-marques found that these are still being combined into a single merged flux. (That may have been the intent at the time, until ocean models were ready to accept this new flux. I know we had extensive conversations about this, but don't remember all of the details.)
This PR separates these two fluxes so that the ocean can separately account for the lnd vs glc-derived runoff and the associated heat fluxes. I have done this in a way so that, if we're coupled to an ocean model that doesn't expect this separate glc-derived runoff (Forr_rofl_glc and Forr_rofi_glc), then it will continue to be merged into the Foxx_rofl and Foxx_rofi …

Keep glc-derived runoff as separate fields to ocn if possible

---

mediator/med_map_mod.F90

Add missing if statement when calling ``med_map_uv_cart3d`` for mapconsf_uv3d case.
Fixes #561

add missing if-statement for uv3d mapping case

---

cime_config/config_component_cesm.xml

Components with "_DATM.\*_MOM6.\*_DROF" in their names have ROF_NCPL set to $ATM_NCPL by default, which can fail the check against $OCN_NCPL.  Changed ATM to OCN.
#551
No
No
This change enables a resolution TL319_t232 in compset G_JRA_RYF in cesm3.0_alphabranch (recently merged into master) to build.  Tests with cesm3_0_beta05 showed that this change does not prevent running.

Make check of ROF_NCPL pass by updating default

---

cime_config/config_archive.xml

Small change to config_archive.xml to include .hx files in addition to the .hi files.
#560
No.   This only affects the behavior of st_archive.
No
There should be no machine dependencies.
I built a B-compset case using the tags specified in the .gitmodules file of a recent (2025-4-22) cesm3.0_alphabranch.
I set namelist values to write out the coupler history files (.hx).
I ran st_archive and confirmed that those files ended up in …

Make st_archive handle the .hx coupler history files

---

cime_config/testdefs/testmods_dirs/drv/interim_restart/shell_commands

this mod requires cime PR 4827
Sets the REST_N value for ERR test to test interim restart feature.  Assumes that the run length of the test is adequate.
Requires https://github.com/ESMCI/cime/pull/4827

add a testmod to test the interim restart feature

---

cime_config/config_component_cesm.xml

Ensure that compsets involving MPAS-O and MPAS-SI maintain reasonable settings for ATM_NCPL.
Normally this defaults to ATM_NCPL=48 with NCPL_BASE_PERIOD=day leading to 1 atm coupling interval every 30 simulated minutes. When the compset long name contains '_MPAS', there's a change to NCPL_BASE_PERIOD=hour.
These changes should help ATM_NCPL stay consistent when the resolution description doesn't contain something like 'a%mpasa...' (e.g. T62_oQU120 grid).
CMEPS Issues Fixed (include github issue #): 
N/A
Are changes expected to change answers? 
No
Any User Interface Changes (namelist or namelist defaults changes)? 
Yes, should require less steps or knowledge to run MPAS-O and MPAS-SI compsets. Modifies env_run.xml in a case, does not modify …

Update ATM_NCPL for MPAS Compsets

---

cime_config/config_component.xml

This pull request explicitly adds the GPU types allowed on Casper and CIRRUS cloud at NCAR.
Contributors other than yourself, if any: N/A
No
No

Add CIRRUS and Casper GPU types

---

mediator/esmFldsExchange_cesm_mod.F90

(cherry picked from commit ae2d923dc5397a61a921fea8dd8d9dd01f614f93)
Fixes typo in the field check.
https://github.com/NorESMhub/CMEPS/pull/37
@monsieuralok, @maritsandstad
For any compsets with with `clm_co2_type=prognostic`, since atmosphere gets non-zero fluxes now.
No.
NorESM SMS tests for compset with `CCSM_BGC=CO2C`.

Bugfix for co2 fluxes comming from land to atmosphere

---

.github/workflows/srt.yml
cime_config/buildnml
cime_config/config_component.xml

Moves some code from cime build.py so that each driver can list its support libraries without messy logic in cime.
https://github.com/ESMCI/cime/pull/4836
Contributors other than yourself, if any: Jian Sun, Jason Boutte

moves liblist to driver buildnml making cime more generic

---

cesm/flux_atmocn/shr_flux_mod.F90

Make qsat calculation in shr_flux_mod.F90 consistent with what's used in CAM, which is also more accurate
Contributors other than yourself, if any: Richard Neale
CMEPS Issues Fixed (include github issue #): 587
Yes. 
NONE
See discussion here: https://github.com/NCAR/amwg_dev/issues/695

Make qsat calculation consistent with CAM

---

cime_config/buildnml

**CMEPS Issues Fixed (include github issue #):**
- Resolves #598
**Are changes expected to change answers?** No; bfb
**Any User Interface Changes (namelist or namelist defaults changes)?** No
A CTSM test was failing and now passes.

Wrap buildnml call of Case.set_value() in non-readonly context
