- cime_config/buildexe
- cime_config/buildnml
Logic was moved from here to the cime Makefile.  Added pop ocn to Bcase runcmp
> rework build

- cime_config/buildexe
undo change that built mediator as part of csm_share library
> undo bld mediator change

- drivers/cime/esm.F90
- mediator/med_phases_restart_mod.F90
Change Description: This PR will fix the issue related with the mediator_read_restart feature.
CIME HASH: cmeps_v0.4 (c6b0dc9)
> fix for mediator restart

- .travis.yml
- cime_config/runseq/runseq_I.py
Change Description: This is a test
CIME HASH:
> change to check travis is working

- cime_config/namelist_definition_drv.xml
Change Description: downcase variable ids in namelist_definition_drv.xml
This is required due to cime issue https://github.com/ESMCI/cime/issues/3144
Testing Completed: CIME_DRIVER=nuopc scripts_regression_tests.py
CIME HASH:
> downcase ids in this file

- cime_config/runseq/runseq_CG.py
Changes two print statements to python3 format. 
CIME HASH:
> Changes print to python3 format

- mediator/med_phases_aofluxes_mod.F90
- mediator/med_phases_prep_lnd_mod.F90
Change Description: Updates needed to be compatible with 
Testing Completed: testlist_drv.xml
all tests are bfb with oct25 baselines EXCEPT for a few fields in the X compsets
new baselines (oct30) were generated
this was run with DRIVER=nuopc but has a **lot of failures that need to be investigated**
CIME HASH: 64129db2f
> Changes needed to work with latest cime master (64129db2f)

- cime_config/buildexe
- cime_config/buildnml
Testing Completed: testing in progress - to be updated
CIME HASH:
> rename fv3gfs to ufsatm

- cime_config/config_component.xml
- mediator/esmFlds.F90
- mediator/med.F90
- mediator/med_constants_mod.F90
- mediator/med_phases_history_mod.F90
Change Description: changes required to update to esmf 8.1.0b05
Testing Completed: scripts_regression_tests 
CIME HASH: 376c2f38c
> Update to esmf8.1

- cime_config/config_component.xml
- mediator/esmFlds.F90
- mediator/med.F90
- mediator/med_constants_mod.F90
- mediator/med_phases_history_mod.F90
> Revert "Update to esmf8.1"

- cime_config/runseq/runseq_D.py
- mediator/med_phases_history_mod.F90
Change Description: bug fixes that were not caught in the previous PR
Testing Completed: testlist_drv.xml
New baselines were created for feb05 that were bfb with jan26 (except for failed tests that were not correctly detected in the jan26 baselines).
CIME HASH: c9df0bfd7
app_cesm-cmeps hash: 41ccbb8
> fixed bugs that were not caught in previous PR

- doc/source/introduction.rst
Update the CMEPS documentation to provide some additional overview sections
on lags, accumulation and averaging as well as the flux calculation grid.
- machines:
- description:
- branch: nuopc_dev …
> Add CMEPS documentation about Lags, Averaging, and the Flux Calculation Grid

- .github/workflows/extbuild.yml
- .travis.yml
- CMakeLists.txt
- cime_config/buildexe
- cime_config/buildnml
- cmake/FindESMF.cmake
- cmake/FindPIO.cmake
- cmake/LibCheck.cmake
- cmake/LibFind.cmake
- mediator/CMakeLists.txt
- nems/util/CMakeLists.txt
- tcipylint
cmake and github actions without directory structure changes.
No source code or directory structure changes in this PR
- machines:
- description:
- branch: nuopc_dev
- hash:
- repository to check …
> cmake and action without dir changes

- mediator/med_io_mod.F90
This fixes bug #124 
Its not clear why this bug was not caught in the standard tests.x
CMEPS Issues fixes #124
- machines:
- details (e.g. failed tests): compared to nov02 and generated nov03 baselines
- description:
- branch: nuopc_dev
- hash: f0c9191
- …
> backing  out changes to med_io_mod.F90 should fix restart problem

- cime_config/runseq/runseq_general.py
- cime_config/testdefs/testlist_drv.xml
- mediator/esmFldsExchange_cesm_mod.F90
- mediator/fd_cesm.yaml
- mediator/med.F90
- mediator/med_internalstate_mod.F90
- mediator/med_phases_prep_glc_mod.F90
Validation fixes for running with evolving CISM
1. CMEPS changes that were introduced as part of the validation of the compset  I1850Clm50SpG -which contains an evolving ice sheet. 
2. This work also needed to be accompanied by associated CISM changes that are in the nuopc_dev hash listed below.
3. Also validated using the CTSM master code base. As a result all baseline comparisons that contain CLM will fail.
4. A new reworked testlist_drv.xml that contains a test fo rI1850CLM50SpG and also removes all SMS tests that had duplicate ERS tests.
Contributors other than yourself, if any: @billsacks 
CMEPS Issues Fixes: #128
Testing performed if application target is CESM:(either UFS-S2S …
> Validation fixes for running with evolving CISM

- cime_config/buildnml
- cime_config/namelist_definition_drv.xml
- mediator/esmFlds.F90
- mediator/esmFldsExchange_cesm_mod.F90
- mediator/fd_cesm.yaml
- mediator/med.F90
- mediator/med_phases_post_lnd_mod.F90
- mediator/med_phases_post_ocn_mod.F90
- mediator/med_phases_prep_glc_mod.F90
Incorporate changes  to enable ocn->glc coupling at multiple levels.
This PR uses dynamic masking in the prep_phases_glc_mod in order to enable sending ocn data to glc. The ocean data is at multiple levels but with associated differences in the ocn bathymetry.
Contributors other than yourself, if any: 
- machines:
- details (e.g. failed tests): compared to cmeps baselines dec06 and created new baseline dec19
- machines …
> changes to enable ocn->glc coupling at multiple leves

- cime_config/config_component.xml
Remove valid_values for GLC_GRID.
This way we don't need to change this xml entry whenever we want to add
a new GLC grid. (None of the other *_GRID variables define valid_values.)
Also, set default_value to UNSET, as for other *_GRID variables.
Contributors other than yourself, if any: none
- machines:
- `ERS_Vnuopc_Ly7.f09_g17_gl4.T1850G.cheyenne_intel`: passes
- …
> Remove valid_values for GLC_GRID

- .github/workflows/bumpversion.yml
Update github bumpversion action to use cmeps prefix and to create annotated tags. 
- machines:
- description:
- description:
Hashes used …
> update to use annotated tags and cmeps prefix

- .github/workflows/bumpversion.yml
Turn on bump version feature.  Make this cmeps1.0.0?
perf(cmeps): add cmeps to tag name
- machines:
- description:
- description:
Hashes …
> bump version

- cesm/nuopc_cap_share/shr_fire_emis_mod.F90
Fixes an issue with how coefficients are applied to individual fire components.### Specific notes
Answer changing for FCfireHIST
SMS_D_Ln9_Vmct.f09_f09_mg17.FCfireHIST.cheyenne_intel (Overall: PASS) details:
SMS_Ld1_Vnuopc.f09_f09_mg17.FCfireHIST.cheyenne_intel (Overall: PASS) details:
> mods to fix fire emissions bug

- cime_config/buildnml
- cime_config/namelist_definition_drv.xml
These are changes needed for CESM needed to fix CAM scam tests and also put in the hooks to bring in wave/ice coupling
- machines:
- description:
- description:
- details (e.g. …
> changes to fix scam and add wave/ice coupling

- cime_config/buildnml
fixes for aquaplanet introduced in cmeps0_13_57
CMEPS Issues Fixed: #291 
- machines:
- description:
- description: …
> fixes for aquaplanet introduced in cmeps0_13_57

- cesm/driver/esm.F90
For scam mode - need to initialize scol_ni and scol_nj for cice model.
- machines:
- description:
- description:
- repository …
> need to initialize these variables

- mediator/esmFldsExchange_cesm_mod.F90
- mediator/fd_cesm.yaml
Addition of wave/cice coupling  fields
Any User Interface Changes (namelist or namelist defaults changes)? Addition of 
SMS.TL319_t061_wt061.GMOM_JRA_WD.cheyenne_intel
> add wave/cice coupling fields

- cime_config/namelist_definition_drv.xml
changes that permits DAE test to work
This PR along with modifications to atm_comp_nuopc.F90 in CAM permits the DAE_Vnuopc.f45_f45_mg37.FHS94.cheyenne_intel to now pass
Are changes expected to change answers? bfb 
Any User Interface Changes (namelist or namelist defaults changes)? New namelists introduced:
```
<entry id="data_assimilation_atm" modify_via_xml="DATA_ASSIMILATION_ATM">
<entry id="data_assimilation_cpl" modify_via_xml="DATA_ASSIMILATION_CPL">
<entry id="data_assimilation_ocn" modify_via_xml="DATA_ASSIMILATION_OCN">
<entry id="data_assimilation_wav" modify_via_xml="DATA_ASSIMILATION_WAV">
<entry id="data_assimilation_glc" modify_via_xml="DATA_ASSIMILATION_GLC">
<entry id="data_assimilation_rof" …
```
> changes that permits DAE test to work (cesm only)

- cesm/driver/util.F90
- cesm/nuopc_cap_share/nuopc_shr_methods.F90
- cime_config/buildexe
- mediator/esmFlds.F90
- mediator/esmFldsExchange_cesm_mod.F90
- mediator/esmFldsExchange_hafs_mod.F90
- mediator/esmFldsExchange_nems_mod.F90
- mediator/med.F90
- mediator/med_map_mod.F90
- mediator/med_merge_mod.F90
- mediator/med_phases_aofluxes_mod.F90
- mediator/med_phases_ocnalb_mod.F90
- mediator/med_phases_post_glc_mod.F90
- mediator/med_phases_prep_atm_mod.F90
- mediator/med_phases_prep_ice_mod.F90
- mediator/med_phases_prep_lnd_mod.F90
- mediator/med_phases_prep_ocn_mod.F90
- mediator/med_phases_prep_rof_mod.F90
- mediator/med_phases_prep_wav_mod.F90
Make the med_fldList fields a linked list instead of an array.   This avoids a lot of small allocations and memory fragmentation.  
Contributors other than yourself, if any: Denise 
CMEPS Issues Fixed: #321 
- machines: cheyenne, intel
- details (e.g. failed tests):  all pass
- machines and compilers cheyenne, intel 
- details (e.g. failed tests):  All pass except expected fails of cesm2_3_alpha10c
- description: gnu and intel
Testing …
> Ll fld list

- mediator/esmFldsExchange_cesm_mod.F90
Nitrogen deposition was being sent from the atmosphere to the land; I added a similar block of code to also send it to the ocean.
Contributors other than yourself, if any: @mvertens provided me with the mods; I used `mrg_type='copy_with_weights'` instead of just `'copy'` and made sure I added it in the atm -> ocn block
CMEPS Issues Fixed (include github issue #): #348
This should be bfb; the only ocean component expecting ndep is still on a branch
no
I haven't done any CIME tests yet; I verified that `cesm2_3_alpha12b` (which uses `cmeps0.14.5`) now correctly passes this field. Happy to run more extensive tests, if …
> Send nitrogen deposition from atm to ocn

- cesm/driver/esmApp.F90
Fix typo that causes model to hang on abort on derecho
> fix hang on abort issue

- cime_config/config_component.xml
Adds support for job_priority on derecho
> support for job_priority on derecho

- cime_config/testdefs/testlist_drv.xml
Updates testlist for new primary test platform derecho.
> more changes for derecho

- .github/workflows/srt.yml
Replace manage-externals with git-fleximod in github workflow.
> replace manage-externals with git-fleximod

- mediator/esmFldsExchange_cesm_mod.F90
One line change to add bilinr_nostd mapping for wav2ice fields.
> Add bilinr_nostd for wav2ice coupling

- .github/workflows/srt.yml
> remove unused variable isPresent

- cime_config/namelist_definition_drv.xml
Adds a connection between xml and namelist variables MODEL_VERSION.
> add connection between xml and fortran

- cime_config/config_component_cesm.xml
> add ATM_NCPL entry for POLARCAP

- .github/workflows/srt.yml
Current main is failing tests in github workflow, this PR is intended to fix it.
> try updating some externals

- cime_config/namelist_definition_drv.xml
Use a description more like what was in cpl7, as suggested by @gunterl
Are changes expected to change answers? No
Any User Interface Changes (namelist or namelist defaults changes)? No (just description)
(None)
I considered trying to improve the documentation of all of the histaux fields, but that feels like a big undertaking. This one field is somewhat different from the others: the others have sets of related variables providing additional flexibility, whereas this one follows more closely what was done in cpl7. So for now I'm just improving the documentation of this field, which is the one requested by @gunterl.
> Improve description of histaux_l2x1yrg

- cime_config/config_archive.xml
Fixes issues with st_archive of rpointer files. 
Contributors other than yourself, if any: Mike Levy
> fix st_archive issues with timestamped rpointer files

- cime_config/config_component.xml
Adds optional support for FTorch.  https://github.com/Cambridge-ICCS/FTorch
This change just adds the XML variables required to support FTORCH.  No negative affects if FTorch is not used. 
> Cmeps1.0.47 ftorch

- cime_config/config_component_cesm.xml
Add ATM_NCPL entry for new NATLx8 grid
CMEPS Issues Fixed (include github issue #): n/a
bfb
no
none
@jedwards4b @rcjwills
> Add ATM_NCPL entry for new NATLx8 grid

- cime_config/namelist_definition_drv.xml
ERR test also needs to be added here so that the correct history files are copied back from case2 to case1.
This fix requires a cime fix as well.
> add the err test to those avoiding end of run restarts

- .github/workflows/srt.yml
- cesm/flux_atmocn/shr_flux_mod.F90
Changes from Jiang-zhu for using shr_flux_mod plus artifacts in testing.
> Shr flux usage
